version: "3.9"
services:
  postgres:
    image: mcs07/postgres-rdkit
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./pg_data:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
