[tool.poetry]
name = "server"
version = "0.1.0"
description = ""
authors = ["Anatol Piven <anatoly.piven@solbeg.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
rdkit = "^2022.9.5"
fastapi = "^0.95.1"
alembic = "^1.10.4"
psycopg2 = "^2.9.6"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
