"""user and compound model

Revision ID: 9dce7f511010
Revises:
Create Date: 2023-05-18 00:44:39.817198

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9dce7f511010"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("is_admin", sa.Boolean(), nullable=True),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("user_id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "compound",
        sa.Column("compound_id", sa.Integer(), nullable=False),
        sa.Column("reg_number", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("structure", sa.String(), nullable=True),
        sa.Column("formula", sa.String(), nullable=True),
        sa.Column("mol_weight", sa.Float(), nullable=True),
        sa.Column("tags", sa.String(), nullable=True),
        sa.Column("mnr", sa.String(), nullable=True),
        sa.Column("ms", sa.String(), nullable=True),
        sa.Column("hplc", sa.String(), nullable=True),
        sa.Column("mp", sa.String(), nullable=True),
        sa.Column("doi", sa.String(), nullable=True),
        sa.Column("cas", sa.String(), nullable=True),
        sa.Column("storage", sa.String(), nullable=False),
        sa.Column("added_by_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("image_url", sa.String(), nullable=True),
        sa.Column("in_stock", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["added_by_id"],
            ["user.user_id"],
        ),
        sa.PrimaryKeyConstraint("compound_id"),
        sa.UniqueConstraint("reg_number"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("compound")
    op.drop_table("user")
    # ### end Alembic commands ###
