"""users and compoubds tables

Revision ID: 6b6ab54e37c3
Revises: 
Create Date: 2024-10-05 11:10:15.970180

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

import settings
from src.auth.hasher import Hasher
from src.compounds.models import Mol

# revision identifiers, used by Alembic.
revision = '6b6ab54e37c3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("create extension btree_gist;")
    op.execute("create extension rdkit;")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('invite_code', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('compounds',
    sa.Column('compound_id', sa.Integer(), nullable=False),
    sa.Column('reg_number', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('structure', Mol(), nullable=False),
    sa.Column('mol_weight', sa.Float(), nullable=True),
    sa.Column('tags', sa.String(), nullable=True),
    sa.Column('mnr', sa.String(), nullable=True),
    sa.Column('ms', sa.String(), nullable=True),
    sa.Column('hplc', sa.String(), nullable=True),
    sa.Column('mp', sa.String(), nullable=True),
    sa.Column('doi', sa.String(), nullable=True),
    sa.Column('cas', sa.String(), nullable=True),
    sa.Column('storage', sa.String(), nullable=True),
    sa.Column('added_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('props', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('in_stock', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['added_by_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('compound_id'),
    sa.UniqueConstraint('reg_number'),
    sa.UniqueConstraint('structure')
    )
    op.create_index('compounds_structure', 'compounds', ['structure'], unique=False, postgresql_using='gist')

    admin_email = settings.ADMIN_USER_EMAIL
    admin_password = Hasher.get_password_hash(settings.ADMIN_USER_PASSWORD)
    op.execute(
        f"INSERT INTO users (email, is_active, is_admin, hashed_password)"
        f" VALUES ('{admin_email}', TRUE, TRUE, '{admin_password}')",
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('compounds_structure', table_name='compounds', postgresql_using='gist')
    op.drop_table('compounds')
    op.drop_table('users')
    # ### end Alembic commands ###
