"""add invite_code to user model

Revision ID: 3410e1f2e6ff
Revises: 4f7733713aea
Create Date: 2024-05-04 02:02:28.621599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3410e1f2e6ff'
down_revision = '4f7733713aea'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('invite_code', sa.String(), nullable=True))
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('user', 'invite_code')
    # ### end Alembic commands ###
